site:
  title: Antora Docs
  start_page: documentation::index.adoc
content:
    sources:
      - url: ../
        branches: [HEAD]
        start_path: docs
ui:
  bundle:
    url: "https://gitlab.com/antora/antora-ui-default/-/jobs/artifacts/master/raw/build/ui-bundle.zip?job=bundle-stable"
    snapshot: true