site:
  title: Antora Docs
  start_page: documentation::index.adoc

content:
    sources:
      - url: ../
        branches: HEAD
        start_path: docs
ui:
  bundle:
    url: ./ui-bundle.icons.zip
    snapshot: true
  supplemental_files: ./supplemental_ui